const enhancer = require('./enhancer.js');
// test away!
describe("enhancment unit tests", () => {
    it("repairs", () => {
        expect(enhancer.repair({name:"Sword", enhancement: 1, durability: 50}))
            .toMatchObject({name:"Sword", enhancement: 1, durability: 100})
        expect(() => enhancer.repair({name:"", enhancement: 1, durability: 50}))
            .toThrow()
        expect(() => enhancer.repair({name:"Sword", durability: 50}))
            .toThrow()
        expect(() => enhancer.repair({name:"Sword", enhancement: 1 }))
            .toThrow()
        expect(() => enhancer.repair({name: 0, enhancement: "", durability: "50"}))
            .toThrow()  
    })

    it("succeeds", () => {
        expect(enhancer.succeed({name:"Sword", enhancement: 1, durability: 50}))
            .toMatchObject({name:"Sword", enhancement: 2, durability: 50})
        expect(enhancer.succeed({name:"Sword", enhancement: 2, durability: 50}))
            .toMatchObject({name:"Sword", enhancement: 3, durability: 50})
        expect(enhancer.succeed({name:"Sword", enhancement: 20, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 20, durability: 100})
        expect(() => enhancer.succeed({name:"", enhancement: 2, durability: 100}))
            .toThrow()
        expect(() => enhancer.succeed({name:"Sword", enhancement: 2}))
            .toThrow()
        expect(() => enhancer.succeed({name:"Sword", durability: 100}))
            .toThrow()
    })

    it("fails", () => {
        expect(enhancer.fail({name:"Sword", enhancement: 1, durability: 50}))
            .toMatchObject({name:"Sword", enhancement: 0, durability: 50})
        expect(enhancer.fail({name:"Sword", enhancement: 5, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 0, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 6, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 1, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 13, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 8, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 15, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 10, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 16, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 6, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 17, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 16, durability: 100})
        expect(enhancer.fail({name:"Sword", enhancement: 19, durability: 100}))
            .toMatchObject({name:"Sword", enhancement: 18, durability: 100})
        expect(() => enhancer.fail({name:"", enhancement: 5, durability: 100}))
           .toThrow()
        expect(() => enhancer.fail({name:"Sword", durability: 100}))
           .toThrow()
        expect(() => enhancer.fail({name:"Sword", enhancement: 5, }))
           .toThrow()
    })
})
